services:
  local-pipeline:
    build:
      context: ./local-pipeline
    env_file:
      - ./local-pipeline/.env
    ports:
      - "8001:8000"
    profiles:
      - local

  backend-api:
    build:
      context: ./backend-api
    env_file:
      - ./backend-api/.env
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_BACKEND_BASE_URL=${VITE_BACKEND_BASE_URL:-http://localhost:8080}
    ports:
      - "5173:80"
    depends_on:
      - backend-api
